### ISSUE TITLE
Question: best way to load custom .pts volumes?

### ISSUE THREAD

**Issue by AnachronicNomad** [Twinklebear/webgl-marching-cubes#1]
Hello!  Thanks so much for taking the time to make this. 

For a project, I was given an unorganized point cloud in the `.pts` format, and asked "can you make this run in a webpage for us?".  Unfortunately, I'm not as familiar with Rust as I'd like to be ::

1. Which command do I run to run the webserver locally?  I've seen a couple examples of `cargo run ...` but wasn't sure of the exact `bin` target to use for this project. 
2. I've read through the `render.js` file and can see the `.raw` files loaded from Dropbox, but do you have any suggestions on how to convert the `.pts` I have into the expected format and then load?  I can see arguments for local loading of the files defined, but not sure how to do this within your setup. 

Any help is appreciated!  Best!

**Comment by Twinklebear** [comment]
You'll have to make some more modifications to this project to get what you want in the end to render the point cloud, but here's to get you started:

## Running the Project

1. Install wasm-pack to compile Rust to wasm: `cargo install wasm-pack`
2. Compile Rust -> wasm: `wasm-pack build -t web --release`
3. Run a web server in the repo root directory, e.g., `python3 -m http.server` and then visit `localhost:8000` in your browser.

## Rendering your Point Cloud

For what you're doing though, I don't think you really need the Rust/wasm side, unless you also want to add some compute or processing in Rust. As you saw, all the rendering and data loading code is in JavaScript, it's just the Marching Cubes algorithm that's implemented in Rust for better performance.

The rendering code you'll also want to change a lot, this application only supports volume rendering and drawing a triangle mesh for the surface. It doesn't have any support for drawing a point cloud. So essentially here in the rendering loop https://github.com/Twinklebear/webgl-marching-cubes/blob/master/js/render.js#L181-L225 you'd need to change it to draw your point cloud data in some way, probably as `gl.POINTS` primitives. I don't know about the `.pts` format so I'd ask your colleagues about the format there. To render it you'd need to get the point positions out, and maybe the colors too.

## Better Starter Project Option

Actually, what you might find to be a more useful starting point is my high quality surface splatting project: https://github.com/Twinklebear/webgl-ewa-splatter . This implements some techniques for high-quality rendering of point-sampled surfaces, think of things like LIDAR scans, etc., where the points represent some surface. This project loads a custom k-D tree format to implement the painting interaction, but you can take that out. You'd modify the loader code here https://github.com/Twinklebear/webgl-ewa-splatter/blob/master/js/ewa-splatter.js#L151-L162 to set `surfelPositions` to an array with a bunch of `vec3f` storing the positions of each point and the `surfelColors` to be a bunch of RGBX, 4 `uint8` per point, storing their colors. Then just search around for any code using the `kdTree` or brushing mode and take it out. If you run into issues adapting that project feel free to open an issue there, but I'll go ahead and close this one.

**Comment by AnachronicNomad** [comment]
You're the best!  Hey out of curiosity, how would you like your projects to be cited?  I know there's a couple templates for MIT Licensed projects + copyleft of the license in any modified projects, but thought I'd double-check.

**Comment by Twinklebear** [comment]
If you're using bibtex you can cite them like:

```bibtex
@misc{<project name>,
	author = {Will Usher},
	year = {2021},
	howpublished = {\url{<the project github url>}},
	title = {{<project name>}}
} 
```

Or if you're not using bibtex, just a link to the Github repo is also fine in a footnote, or in the references something that has like my name/github url/etc. kind of info.
